### ISSUE TITLE
Logo for the GPM

### ISSUE THREAD

**Issue by saqibameen** [ahmadawais/gatsby-package-manager#1]
I have created two logos for GPM. If you'd like you can use it for the CLI.

![gpm logo](https://i.imgur.com/uDQOYDR.jpg)

**Comment by ahmadawais** [comment]
I like both of them. Maybe the second set. Send me high res versions. Thanks man.

**Comment by saqibameen** [comment]
You can find the high res photo [here](https://i.imgur.com/2tbTDHa.jpg) and download the PSD [here](https://www.dropbox.com/sh/qqckbfnbzm8l2qr/AAD6pp2-GXIylBqW-F8WgLAKa?dl=0).

**Comment by ahmadawais** [comment]
The new logo is here. Thanks a lot, @saqibameen! 👌
